# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import todolist_pb2 as todolist__pb2


class TodoListStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTodolist = channel.unary_unary(
                '/proto.TodoList/GetTodolist',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=todolist__pb2.TodoListResponse.FromString,
                )


class TodoListServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTodolist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TodoListServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTodolist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTodolist,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=todolist__pb2.TodoListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TodoList', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TodoList(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTodolist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.TodoList/GetTodolist',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            todolist__pb2.TodoListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
