# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todolist.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etodolist.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"1\n\x0cTodoListData\x12\r\n\x05title\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\x04\"H\n\x10TodoListResponse\x12&\n\ttodoLists\x18\x01 \x03(\x0b\x32\x13.proto.TodoListData\x12\x0c\n\x04size\x18\x02 \x01(\r2J\n\x08TodoList\x12>\n\x0bGetTodolist\x12\x16.google.protobuf.Empty\x1a\x17.proto.TodoListResponseB\x08Z\x06proto/b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todolist_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006proto/'
  _TODOLISTDATA._serialized_start=54
  _TODOLISTDATA._serialized_end=103
  _TODOLISTRESPONSE._serialized_start=105
  _TODOLISTRESPONSE._serialized_end=177
  _TODOLIST._serialized_start=179
  _TODOLIST._serialized_end=253
# @@protoc_insertion_point(module_scope)
